service: db21music-api
provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-west-2

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
        - "s3:PutObject"
        - "cloudformation:DescribeStackResource"
      Resource: "arn:aws:s3:::myS3Bucket/*"
plugins:
  - serverless-wsgi
  - serverless-python-requirements
custom:
  wsgi:
    app: api.app
    packRequirements: false
functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
package:
  exclude:
    - node_modules/**
    - venv/**
    - venv-linux/**