service: db21music-api
provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-2
plugins:
  - serverless-wsgi
  - serverless-python-requirements
custom:
  wsgi:
    app: api.app
    packRequirements: false
functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'